# Generated by Django 5.2.4 on 2025-07-20 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="pokemon_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokeapi_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "types",
                    models.ManyToManyField(
                        related_name="pokemons", to="secure_poke_api.pokemontype"
                    ),
                ),
            ],
        ),
    ]
